name: iOS

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    name: Build and Test
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: xcodebuild test
      run: |
        set -o pipefail
        xcodebuild clean test -project NavigatableCollectionSampleApp/NavigatableCollectionSampleApp.xcodeproj -scheme NavigatableCollectionSampleApp -destination "platform=iOS Simulator,name=iPhone 11" | xcpretty
